### ISSUE TITLE
Add LICENSE[.txt] file

### ISSUE THREAD

**Issue by crepererum** [mewwts/pyudorandom#1]
Please add a `LICENSE` or `LICENSE.txt` file that contains the actual text of the MIT license. This would help others to instantly see what license applies and we be --- in legal terms --- somewhat safer than just an attribute in `__init__.py`.

I think I shouldn't provide a PR for this, since this would mean that I set the license for your work, which would be clearly the wrong signal.

**Comment by mewwts** [comment]
I've create a LICENSE file. Thanks for bringing this up!
